### PR TITLE
Complete "Outreach" form

### PR DESCRIPTION
**Pull request by Kirk-Esterline**
**Work Completed**
- Added the remaining "responseDetails" and "clientWork" elements to the "Outreach form.
- Elements were added in the same manner as the existing elements to create a longer form.
- Headings were also added to separate between contact, response, and client work.

**Ideas for further development** (Updated 10/08/2023)
- Add a check for whether the client was contacted before adding response or work details.
- ResponseYes is now currently a checkbox.  Consider the response to be a drop down of "Yes", "No", and "Maybe Later".  This might give the user a better indication of whether they should reach out to the client later.

### CODE REVIEW

**Review by devlarabar — CHANGES_REQUESTED** [review]
Hey, thanks for working on this! I have a couple notes. I see that there's a merge conflict, this was likely caused by not pulling the most recent changes before creating your PR. Could you please run `git pull origin main` and resolve?

There's also a typo on line 190, `resonse` should be `response`: `value={outreach.responseDetails.resonseYes}`.

Once those changes are made, I'll review again and test that everything works as intended :thumbsup:

**Comment by Kirk-Esterline** [comment]
I addressed the merge conflict and fixed the typo.  Additionally, updated classNames to reflect the existing "checkbox".

**Comment by devlarabar** [comment]
It looks like we both made PRs at the exact same time, so there are still (different) conflicts unfortunately. If you wouldn't mind resolving again, I'll go ahead and merge afterward! I really appreciate your help!

**Comment by Kirk-Esterline** [comment]
Sounds good. I'll take another look later today when I have some time.

**Review by devlarabar — APPROVED** [review]
LGTM, thank you for working on this!

**Pull request merged**
