### PR TITLE
Landing page

### LINKED ISSUE #20: Landing Page Design & Construction
It's time to start building our landing page! We need to both design and code the landing page (on the root route). Since users cannot see the features of the app without being logged in, it would be helpful to include screenshots and descriptions of the various features (and upcoming features) in the landing page to encourage new users to create accounts.

The screenshots should include desktop, tablet, and mobile views to display that the app works well on all screen sizes. Since the app is still in the early stages of development, placeholder images will work fine for now. [This](https://placehold.co/) is a great website for placeholders.

A small blurb describing the importance of freelancing for the start of a developer's tech career would be helpful as well!

Discussions regarding the design can be held here or in our thread on Discord.

### PR DESCRIPTION
**Pull request by Kirk-Esterline**
Commit coauthored with Ahmed Hamdy

### Description

Built out the landing page to resemble the design layout.
We added a ul, two imgs, as well as necessary tailwind classes to page.jsx.

### Testing

We tested on different browsers and screen sizes to check responsiveness.

### Did you change the schema?

- [ ] Yes
- [ X ] No

### Issue

Closes #20

### CODE REVIEW

**Review by devlarabar — CHANGES_REQUESTED** [review]
Hey Kirk and @AhmedHHamdy ! I really appreciate your hard work on this! The desktop layout looks beautiful. Very clean and crisp.

Something that stands out to me is the responsiveness. The layout doesn't adjust for mobile as in Karissa's original design referenced in the [landing page issue](https://github.com/devlarabar/100freelancers/issues/20). This is what it looks like when I resize:

Screenshot 2023-11-10 141756
Screenshot 2023-11-10 141806
Screenshot 2023-11-10 141829

It starts to look off between 860-1100px wide. I know Karissa's mobile design includes swiping between mobile screenshots, but for simplicity, it would be fine for now to just include one screenshot and we can enhance it in a future sprint.

For the "mid" sizes (smaller monitors and tablets), we can probably include the desktop and mobile screenshot images, but move them from the right side of the page to below the "View", "Add", and "Track" text. Then for super small screens like mobile, omit the desktop screenshot entirely and only show the mobile screenshot. Hope that makes sense - let me know if I should clarify!

Aside from this, I noticed some comments in `globals.css` that can be removed to keep the file clean and readable.

Thanks again for working so hard on this, and please feel free to ping me in Discord any time if you need help!

**Comment by Kirk-Esterline** [comment]
Thank you for the quick and clear feedback!

I added several break points to make the page responsive to screen size.  On smaller screen sizes the images are beneath the "view" "add" and "track" text.  On larger screens the text and images are side by side however, the images will respond by either being stacked or overlapped depending on screen size.  I made that decision to make the layout feel less cramped in the 'large' breakpoint without needing to make either image smaller.

Let me know if additional changes are required.

**Comment by Kirk-Esterline** [comment]
With Ahmed's help we added aditional break points to keep the text and images side by side on a wider range of screens, and adjusted the styling on mobile screen sizes to be more mobile specific.

**Review by devlarabar — APPROVED** [review]
Excellent! Thank you both so much for implementing the changes quickly. Everything looks great to me 👍

**Pull request merged**
